--use academy_top

--create table students
--(
--id int not null identity(1,1) primary key,
--studName nvarchar(50) not null,
--studFname nvarchar (50) not null,
--studAge int not null,
--gropeName nvarchar (50) not null,
--grants int 
--)
--alter database scoped configuration set identity_cache=off 